Base name = 20230416_16_35_42_Cage4278764_Animal01_STRAINFOSTRAPXAI9TDTOMATO_Female_Cohort4_BEHAVIORTMTWATERCONTROL
Looking for images in /athena/listonlab/scratch/dje4001/lightsheet_scratch/WATERCONTROL/lightsheet/raw/20230416_16_35_42_Cage4278764_Animal01_STRAINFOSTRAPXAI9TDTOMATO_Female_Cohort4_BEHAVIORTMTWATERCONTROL...
Found 135128 compatible images
Setting up 112 workers...
Pystripe batch processing progress:
  0%|          | 0/135128 [00:00<?, ?it/s]  0%|          | 1/135128 [02:58<6711:27:50, 178.80s/it]  0%|          | 4/135128 [02:59<1278:58:15, 34.07s/it]   0%|          | 7/135128 [02:59<593:33:32, 15.81s/it] slurmstepd: error: *** JOB 15321 STEPD TERMINATED ON c0009 AT 2023-09-12T17:08:23 DUE TO JOB NOT ENDING WITH SIGNALS ***
slurmstepd: error: Container 200492 in cgroup plugin has 37 processes, giving up after 383 sec
  0%|          | 113/135128 [05:12<66:31:54,  1.77s/it]  0%|          | 116/135128 [05:16<65:54:17,  1.76s/it]  0%|          | 121/135128 [05:17<60:49:52,  1.62s/it]  0%|          | 134/135128 [05:19<48:09:55,  1.28s/it]  0%|          | 135/135128 [05:20<47:13:08,  1.26s/it]  0%|          | 137/135128 [05:21<45:21:14,  1.21s/it]  0%|          | 140/135128 [05:21<39:57:14,  1.07s/it]  0%|          | 145/135128 [05:28<42:46:05,  1.14s/it]  0%|          | 149/135128 [05:33<44:21:25,  1.18s/it]  0%|          | 151/135128 [05:36<45:23:52,  1.21s/it]  0%|          | 153/135128 [05:38<43:29:57,  1.16s/it]  0%|          | 155/135128 [05:42<51:03:17,  1.36s/it]  0%|          | 157/135128 [05:43<42:21:58,  1.13s/it]  0%|          | 171/135128 [05:44<16:38:21,  2.25it/s]  0%|          | 178/135128 [05:47<15:14:48,  2.46it/s]  0%|          | 187/135128 [05:48<11:26:49,  3.27it/s]  0%|          | 212/135128 [05:48<4:57:24,  7.56it/s]   0%|          | 212/135128 [06:00<4:57:24,  7.56it/s]  0%|          | 225/135128 [07:51<112:05:30,  2.99s/it]  0%|          | 230/135128 [07:53<97:48:39,  2.61s/it]   0%|          | 232/135128 [08:01<102:20:02,  2.73s/it]  0%|          | 234/135128 [08:01<92:48:45,  2.48s/it]   0%|          | 236/135128 [08:04<86:48:02,  2.32s/it]  0%|          | 240/135128 [08:09<76:27:38,  2.04s/it]  0%|          | 247/135128 [08:11<50:28:04,  1.35s/it]  0%|          | 248/135128 [08:16<62:50:09,  1.68s/it]  0%|          | 258/135128 [08:17<31:34:02,  1.19it/s]  0%|          | 263/135128 [08:23<34:33:44,  1.08it/s]  0%|          | 269/135128 [08:25<28:51:39,  1.30it/s]  0%|          | 274/135128 [08:30<30:03:54,  1.25it/s]  0%|          | 279/135128 [08:31<23:16:02,  1.61it/s]  0%|          | 281/135128 [08:33<25:49:08,  1.45it/s]  0%|          | 284/135128 [08:34<24:03:50,  1.56it/s]  0%|          | 285/135128 [08:41<46:41:25,  1.25s/it]  0%|          | 294/135128 [08:45<30:03:56,  1.25it/s]  0%|          | 312/135128 [08:49<17:02:58,  2.20it/s]  0%|          | 330/135128 [08:50<9:46:55,  3.83it/s]   0%|          | 337/135128 [10:30<117:32:56,  3.14s/it]  0%|          | 340/135128 [10:38<116:32:24,  3.11s/it]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 388, in filter_subband
    img_log = np.log(1 + img)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 24.4 MiB for an array with shape (1600, 2000) and data type float64
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/fs01/dje4001/anaconda3/bin/pystripe", line 8, in <module>
    sys.exit(main())
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 972, in main
    batch_filter(input_path,
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 824, in batch_filter
    list(tqdm.tqdm(pool.imap(_read_filter_save, args, chunksize=chunks), total=len(args), ascii=True))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 652, in _read_filter_save
    read_filter_save(**input_dict)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 607, in read_filter_save
    fimg = filter_streaks(img, sigma, level=level, wavelet=wavelet, crossover=crossover, threshold=threshold, flat=flat, dark=dark)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 471, in filter_streaks
    foreground_filtered = filter_subband(foreground, sigma[0], level, wavelet)
  File "/home/fs01/dje4001/anaconda3/lib/python3.8/site-packages/pystripe/core.py", line 388, in filter_subband
    img_log = np.log(1 + img)
numpy.core._exceptions.MemoryError: Unable to allocate 24.4 MiB for an array with shape (1600, 2000) and data type float64
